# Site settings
title: CYBERSOCKS
description: "Cybersocks Regional Competition 2016"
url: "https://cybersocks.org"
admin: "admin@cybersocks.org"

# Build settings
markdown: kramdown
permalink: /:title

# Custom variables
version: "2.0"
timezone: Asia/Kuala_Lumpur
kramdown:
  input: GFM

# Compression
compress_html:
  clippings: all
sass:
  style: compressed
