# Site settings
title: CyberSOCKS
description: "CyberSOCKS Regional Competition 2016"
url: "https://cybersocks.org"
domain: "cybersocks.org"

# Build settings
markdown: kramdown
permalink: /:title

# Custom variables
version: "2.3.3"
timezone: Asia/Kuala_Lumpur
kramdown:
  input: GFM
gems:
  - jekyll-sitemap

# Compression
compress_html:
  clippings: all
sass:
  style: compressed

# Data
location: Casuarina @ Meru, Ipoh, Perak, Malaysia
date:
  quals: 22nd – 23rd October 2016
  regional: 10 December 2016
link:
  utphax: https://utphax.cyberhax.club/
